# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cbcdce34d22176d82d6e61561ca1aeb21c9489dec9c9623d310ebc98dd97b14bc0b46bf3bfd21592acaf079db04ab6ded11ab703e00e3e0e44918eeebc172f6

test:
  secret_key_base: 4f06f11bb17637ed5119ca1818578e01c2ca3a98d538338cd3da07f4736ddae52e9658888dd7c7bc90b779e7708b196479c9af0d6018d3b9a7400dfe64f772b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
